### ISSUE TITLE
Route 53 DNS Proxy broken after upgrade to Foreman 1.14.1 on Ubuntu 14.04

### ISSUE THREAD

**Issue by pauldsmyth** [theforeman/smart_proxy_dns_route53#14]
I am no longer able to create ec2 hosts as the route 53 dns proxy is broken:

D, [2017-02-09T14:53:33.957926 ] DEBUG -- : Providers ['dns_route53'] are going to be configured for 'dns'
E, [2017-02-09T14:53:33.964124 ] ERROR -- : Disabling all modules in the group ['dns_route53', 'dns'] due to a failure in one of them: cannot load such file -- smart_proxy_dns_plugin_template/dns_plugin_template_main
D, [2017-02-09T14:53:33.964165 ] DEBUG -- : ["/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'", "/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'", "/usr/lib/ruby/vendor_ruby/smart_proxy_dns_route53/dns_route53_configuration.rb:4:in `load_classes'", "/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:294:in `load_classes'", "/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:243:in `load_settings'", "/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:81:in `block in load_provider_settings'", "/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:80:in `each'", "/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:80:in `load_provider_settings'", "/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:155:in `block in initialize_plugins'", "/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:155:in `each'", "/usr/share/foreman-proxy/lib/proxy/plugin_initializer.rb:155:in `initialize_plugins'", "/usr/share/foreman-proxy/lib/launcher.rb:134:in `launch'", "/usr/share/foreman-proxy/bin/smart-proxy:6:in `<main>'"]

**Comment by domcleal** [comment]
Version 3.0.1 has been released with the fix, thanks for the bug report. Packages will be available within the next day or two.

**Comment by pauldsmyth** [comment]
Thanks Dominic for your speedy assistance with this
