### ISSUE TITLE
HTTP Proxy

### ISSUE THREAD

**Issue by gioxchopper** [theforeman/smart_proxy_dns_route53#15]
We have a smart proxy running in AWS, with no public IP. Everything else seems to be able to use our HTTP_PROXY, except this route53 plugin. Is there a configuration option that needs to be set for this to work, or is this not supported?

Our current setup:
CentOS  6.7
Foreman v1.12.0
smart_proxy_dns_route53  -v2.0.0
route53 v0.4.0

**Comment by ekohl** [comment]
This plugin relies on the route53 gem. Looking at [the code](https://github.com/pcorliss/ruby_route_53/blob/f96fab52931f069ba4b5fddb291aa53c7412aa52/lib/route53/connection.rb#L23) it's standard ruby behaviour. On CentOS6 you're using Ruby 1.8.7 which [does not supported](http://ruby-doc.org/stdlib-1.8.7/libdoc/net/http/rdoc/Net/HTTP.html#method-c-new) it. Ruby 2.0 (default on CentOS7) [does support](https://docs.ruby-lang.org/en/2.0.0/Net/HTTP.html#class-Net::HTTP-label-Proxies) it though.
