### ISSUE TITLE
RPM packaging

### ISSUE THREAD

**Issue by domcleal** [theforeman/smart_proxy_dns_route53#3]
Submit this plugin to https://github.com/theforeman/foreman-packaging/tree/rpm/develop.

Needs:
- rubygem-builder for EL6, already available in EPEL7 and F19 (old SRPM available in Koji)
- rubygem-ruby-hmac for EL6/7, already in F19 (old SRPM available in Koji)
- rubygem-route53 for all
- rubygem-smart_proxy_dns_route53 for all

**Comment by dLobatog** [comment]
rubygem-builder seems to be available everywhere thanks to sclo-ror42 no?

**Comment by domcleal** [comment]
Smart proxy plugins aren't SCL, so wouldn't use packages from sclo-ror42.

**Comment by dLobatog** [comment]
RPM packaging on the making on https://github.com/theforeman/foreman-packaging/pull/1182

**Comment by ekohl** [comment]
Related PR has been merged so this can be closed.
