### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by domcleal** [theforeman/smart_proxy_dns_route53#4]
Submit this plugin to https://github.com/theforeman/foreman-packaging/tree/deb/develop.

Needs:
- ruby-builder - appears to be available for all platforms already
- ruby-hmac - appears to be available for all platforms already
- ruby-nokogiri - appears to be available for all platforms already
- ruby-route53 - missing on all
- ruby-smart-proxy-dns-route53

**Comment by mmoll** [comment]
this got packaged in theforeman/foreman-packaging@cc2d1ed

**Comment by ekohl** [comment]
Thanks!
