### ISSUE TITLE
:dns_ttl: from dns.yml not used

### ISSUE THREAD

**Issue by jlory** [theforeman/smart_proxy_dns_route53#8]
It looks like you can't change the ttl value for created records. The ttl is taken from foreman-proxy/modules/dns/dns.rb

Edit: I'll do a fix for that later this week.

**Comment by domcleal** [comment]
I've just merged a set of changes that make the plugin compatible with the 1.11 smart proxy, and I think this might now load the TTL properly from settings.  If you want to fix it for the existing 1.x version (compatible with 1.10) then propose the PR against the `1.0-stable` branch that I just pushed.  Thanks!

**Comment by ekohl** [comment]
Given the age of this issue and that a fix should be in released versions I'm going to assume this is fixed and close the issue. If this is not the case, please re-open it.
