### ISSUE TITLE
Route 53 Entries being deleted on Puppet edit and update

### ISSUE THREAD

**Issue by pauldsmyth** [theforeman/smart_proxy_dns_route53#9]
I'm not sure if this is the correct place to put this, since the most recent update of Foreman to 1.13.1 route 53 entries are being deleted whenever I make a change via puppet to a host. The relevant log entries are attached with obfuscation of domain names/ips. 

From what I can see, puppet is attempting to delete and recreate the entrie even though they haven't changed and while this may be a change in puppet, I believe this is related to a annoyance I've seen already. 

When I've created host using provisioning, there have been occasions where a mistake has been made causing me to delete and recreate the host. This fails because when it tries to add the Route 53 entry it fails with an error that the entry already exists. The work around is to add the entry through the Amazon console and the delete it again. The entry can then be created through the smart proxy. If this underlying issue was resolved I believe my current issue would go away. It appears to me to be the same cause.

Apologies if this seems a little rambling. 

[foreman-route53.stack.trace.txt](https://github.com/theforeman/smart_proxy_dns_route53/files/568607/foreman-route53.stack.trace.txt)

**Comment by dmitri-d** [comment]
We don't track issues on github. Could you please file one at http://projects.theforeman.org/projects/smart-proxy/issues? It would be helpful if you include both foreman and proxy logs when you create a ticket.

**Comment by domcleal** [comment]
GitHub issues is correct for this project - it's a plugin, not part of the Smart Proxy.

**Comment by pauldsmyth** [comment]
Apologies witlessbird, I just create the issue on the tracker under ec2, please file to move it

**Comment by dmitri-d** [comment]
Nods, my apologies, just noticed the issue was filed for a plugin, not proxy iteself. Ignore my comment.

**Comment by dmitri-d** [comment]
It would be useful to see proxy logs in addition to foreman logs, however.

**Comment by domcleal** [comment]
Yeah, though reading the description I'm unsure that this is an issue in this plugin specifically.

I don't see the errors in the log that are mentioned in the description, about the entries already existing.

**Comment by pauldsmyth** [comment]
Proxy log has not been written to since 18th October.

**Comment by domcleal** [comment]
Not sure there's much we can suggest without having the corresponding logs - fix that first, try restarting the service, check permissions etc.

**Comment by pauldsmyth** [comment]
Restarted, can't see any issues with perms. Will attempt to change a test host to see if it kicks into life but this host was rebooted for application of Dirty Cow patch on 31st October so I can't see why it's not writing.

**Comment by pauldsmyth** [comment]
Ok I've removed the proxy.log and restarted the service to let it recreate which it has done. I've just updated another host and seen exactly the same behaviour. This is the only entry in the proxy.log after the host update has run and removed the Route 53 entry:

"# Logfile created on 2016-11-03 10:37:19 +0000 by logger.rb/31641"

**Comment by dmitri-d** [comment]
I don't think foreman is using this proxy.

**Comment by pauldsmyth** [comment]
How is Foreman updating route 53 entries if not through the route53 smart proxy?

**Comment by pauldsmyth** [comment]
Just dissociated the smart proxy from the relevant domain but not the reverse domain. Result after applying update is that the A record is still there but the reverse PTR record is gone. Foreman is absolutely using this proxy.

**Comment by dmitri-d** [comment]
Check the log level? Set it to debug if it's not already set. You should be seeing at least an entry per request.

**Comment by pauldsmyth** [comment]
Is it possible to set this for the proxy without setting it for the whole of Foreman?

**Comment by dmitri-d** [comment]
Yes, proxy process is completely independent of foreman and has its own settings.

**Comment by pauldsmyth** [comment]
[foreman-proxy.log.txt](https://github.com/theforeman/smart_proxy_dns_route53/files/568789/foreman-proxy.log.txt)
Ok I have some logging

**Comment by pauldsmyth** [comment]
I'm off to get a coffee and bang my head against a wall

**Comment by pauldsmyth** [comment]
Some further info, I have Cloudtrail log to graylog. I can see the delete entries from foreman but no create entries.

**Comment by dmitri-d** [comment]
I don't think there's an issue with proxy or route53 provider. It looks more like an issue with host update orchestration. I would suggest using http://projects.theforeman.org/issues/17197 instead of this ticket.

**Comment by pauldsmyth** [comment]
Ok

**Comment by pauldsmyth** [comment]
Trouble is it seems to being ignored over there and this is a show stopper

**Comment by domcleal** [comment]
The bug in Foreman is being addressed, so I'm going to close this now, thanks for the report.

I think there _may_ still be an issue with detection of DNS records ("This fails because when it tries to add the Route 53 entry it fails with an error that the entry already exists"), though it's possible that it's due to resolver caching. Foreman does have an issue with rDNS caching, but it's possible there's another issue - please feel free to file a bug with more precise details about that if you wish.
